- README.md
The logo in this README worked but I changed it to the one we are using on `leveldb.org`. Also I think it's pretty cool to link to a logo from a site we are hosting. Also makes it easier to replace it later with another svg if we like.
> update logo and copyright

- README.md
- package.json
I cleaned up some stuff and added some links in README to point to the discussion behind the removal and also a link to the wiki page.
> Remove ws, update

- lib/levelup.js
When do a `db.get`, check for `.notFound` on `err` to determine if a `NotFoundError` should be created.
[Related downstream issue](https://github.com/substack/level-create-batch/issues/2)
> check notFound on err

- lib/levelup.js
- test/batch-test.js
- test/common.js
- test/get-put-del-test.js
- test/init-test.js
- test/null-and-undefined-test.js
- test/optional-leveldown-test.js
This adds the errors to the available namespace so that it can be used from `levelup`.
```javascript
var levelup = require('levelup');
var db = levelup('./somedata');
db.get('somekey', function(err, value) {
if (err instanceof levelup.errors.NotFoundError) {
return db.put('somekey', 'somedata', function (err) {
if (err) {
throw err;
}
});
} else if (err) {
throw err;
}
});
```
> Added errors to the available namespace when requiring 'levelup'.

- .travis.yml
This replaces 0.10 with 0.12 and iojs. Should we keep 0.10 or carry on?
/cc @jcrugzz @juliangruber @mcollina @rvagg
> node 0.12 and iojs on travis

- README.md
The `get` options paragraph didn't mention that `value` objects also adhrere to `valueEncoding`. I just removed the duplicate paragraph with less information and stated that `get` is the same as `put` - seems more DRY.
> Changed options for get to same as put

- README.md
I'm also wondering if we should try to reformulate a bit. Since I'm not a native english speaker I might be off. In the beginning we mention `bi-directional iterators` as one of the features and we say this in plural, i.e. there are at least two types of iterators.
But since `write-stream` has been removed, does this mean we have one type of iterator, or are there still several types of iterators? Or is it a single bi-directional iterator that is exposed by `createReadStream()`? If there are different types of iterators I think we should be more specific in what they are to get rid of ambiguity.
> remove reference to write-stream and iterators

- lib/codec.js
- lib/levelup.js
- lib/util.js
- test/binary-test.js
- test/deferred-open-test.js
- test/encoding-test.js
- test/init-test.js
- test/inject-encoding-test.js
- test/json-test.js
- test/open-patchsafe-test.js
- test/read-stream-test.js
We undocumented it a while I go, now it's time to finally kick it out for `1.0.0`.
> remove encoding option

- lib/levelup.js
- lib/read-stream.js
- package.json
this depends on https://github.com/Level/deferred-leveldown/pull/6
This removes deferred iterator logic from levelup as that's handled in the pull request above. Also the readable stream interface is one step closer to being ready to be split out into its own module.
> refactor iterators using new deferred-leveldown

- test/benchmarks/stream-bench.js
This needed to be touched since we removed writestreams. i also added benchmarks for different `{ keys, values }` combinations and made sure they run often enough so performance is a stable characteristic.
Current output:
```bash
∴  benchmarks (master) : node stream-bench.js
Filled source! Took 2702ms, reading data now...
Done! Took 1682ms with {}
Done! Took 1336ms with {"keys":true}
Done! Took 1083ms with {"values":true}
Done! Took 1222ms with {"keys":true,"values":true}
Done! Took 1112ms with {}
Done! Took 1134ms with {"keys":true}
Done! Took 1065ms with {"values":true}
Done! Took 1182ms with {"keys":true,"values":true}
Done! Took 1272ms with {}
Done! Took 1086ms with {"keys":true}
Done! Took 1106ms with {"values":true}
Done! Took 1416ms with {"keys":true,"values":true}
```
The need for …
> fix stream-bench.js

- lib/levelup.js
- test/appromixate-size-test.js
- test/get-put-del-test.js
Since it has been undocumented for a while and we're about to make a major release.
We can also use [util.deprecate](https://iojs.org/api/util.html#util_util_deprecate_function_string) first, but I'd prefer plain removing it.
> remove .approximateSize()

- lib/util.js
- test/optional-leveldown-test.js
I'm trying to iron out some problems we get when trying to require `leveldown` (see https://github.com/Level/leveldown/issues/190).
Currently we give the advice to try and `npm install leveldown` if requiring it doesn't work. This error message isn't very helpful when you before receiving the error actually did install it.
This PR uses the error message we get in `try/catch` so we can get more information (e.g. the current ABI version and the expected ABI version).
> improve error message when trying to require leveldown

- README.md
- lib/levelup.js
- lib/util.js
- package.json
- test/benchmarks/engines/levelup-nosnappy.js
- test/benchmarks/engines/levelup.js
- test/benchmarks/package.json
- test/common.js
- test/deferred-open-test.js
- test/encoding-test.js
- test/idempotent-test.js
- test/init-test.js
- test/inject-encoding-test.js
- test/json-test.js
- test/leveldown-substitution-test.js
- test/null-and-undefined-test.js
- test/open-patchsafe-test.js
- test/read-stream-test.js
this changes the api from
```js
var db = levelup(location, { db: leveldown })
```
to
```js
var db = levelup(leveldown(location))
```
this is for v2
> Remove location argument

- README.md
This fixes the "License & copyright" link from the intro. Sorry I couldn't do something more awesome.
> readme: small typo

- README.md
- lib/batch.js
- test/batch-test.js
Following up on #371 with a patch, [per request](https://github.com/Level/levelup/issues/371#issuecomment-146499907).
This PR tracks and exposes the length of the operations queues of chained batch objects:
```javascript
var assert = require('assert')
var levelup = require('levelup')
var memdown = require('memdown')
var level = levelup({ db: memdown })
var batch = level.batch().put('a', '1').put('b', '2').del('c')
// New
assert.equal(batch.length, 3)
batch.put('d', '4')
// New
assert.equal(batch.length, 4)
```
@juliangruber, you mentioned using a getter, but I don't think you'd decided. Please let me know if I should rewrite with `defineProperty`.
Many thanks to all involved!
> Track and expose lengths of chained batch operations queues

- .travis.yml
- package.json
`nsp` reports a problem becase `levelup` is using a version of `semver` with a known vulnerability, see https://nodesecurity.io/advisories/31
I originally started looking at updating `level-sublevel` but there were just too many changes to be made *just* to be able to update `semver`, so I think we should release `0.19.1` instead, and then `level-sublevel` can at least use that version of `levelup` to start with.
> bump semver for nsp fix

- lib/util.js
The missing file ending resulted in build issues in our project.
> Add .json file ending to leveldown package

- lib/leveldown.js
- lib/levelup.js
- lib/util.js
- package.json
- test/browserify-test.js
- test/optional-leveldown-test.js
Following on from #423.
This patch pulls the LevelDOWN loading and version checking code out of `lib/util.js` into its own, separate module.  It also modifies `package.json` to prevent Browserify from packing the new module, which in turn prevents it from packing the project's `package.json` file.
I mentioned a different approach in #423: Using a prepublish lifecycle script to extract `devDependencies.leveldown` into a one-line JSON file for the version checking code to `require`.  This modular approach seems cleaner, and leverages mechanisms, like the `browser` field, that `levelup` is already using.
> Pull LevelDOWN loader out to non-Browserified module

- lib/levelup.js
Hi there!
This is the quick fix for the issue described on: https://github.com/Level/levelup/issues/426
I intended to come up with a full PR that would run tests in the browser as well, but due to the quantity and the fact that they rely on `fs`, I haven't been able to finish this quickly, you can see progress at https://github.com/diasdavid/levelup/tree/test/browser
Here is what I propose: Merge this PR and do a patch release so that no user hits this breakage when using it in the browser. After, finish browser testing so that this situation doesn't happen again.
> fix: avoid calling getLevelDOWN if not present

- lib/levelup.js
- package.json
- test/browserify-test.js
- test/data/browser-throws.js
- test/data/browser-works.js
`options.db` _must_ be set when `levelup` is browserified, this patch makes it clearer if/when this happens
* undos https://github.com/Level/levelup/pull/427
* related https://github.com/Level/levelup/pull/424
> throw more descriptive error if db factory is not a function

- README.md
- lib/levelup.js
Enable us to use `import levelup from 'levelup'` by adding `default` export.
> add default export

- README.md
As discussed in #456, this changes "database" / "store" / "backend" / etc into "underlying store".
> Readme: prefer 'underlying store'

- .travis.yml
- lib/batch.js
- lib/levelup.js
- lib/promisify.js
- package.json
- test/maybe-error-test.js
This is for issue #516
I believe the node version badge will update on next release since it’s based on package.json engines field.
> restoring node 4 support

- README.md
I think this makes the `README` a little bit cleaner and more readable. Also easier to maintain if new sections are added.
The only thing I'm not happy with is that I can't get links working for sections with multiple words, so changed `Supported Platforms` to `Platforms`, `Promise Support` to `Promises` etc.
@vweevers Know any l337 markdown tricks to make that work?
> use markdown links to get rid of <a href> and <a name>

- lib/levelup.js
- test/browserify-test.js
As mentioned on #524 - I changed it to make the error message clearer.
Previously was **must provide db**,
changed to **The first `db` argument must be an abstract-leveldown compliant store**.
> improve 'must provide db' error message to make it clearer

- .gitignore
- .travis.yml
- README.md
- package.json
Closes https://github.com/Level/levelup/issues/459
> Add nyc and coveralls

- CHANGELOG.md
- CONTRIBUTORS.md
- README.md
- UPGRADING.md
- package.json
Squash on merge. Closes #614, closes #615, closes #620.
The third commit adds a lot of diff noise, because `hallmark` has a custom list item indent option. Should we remove that from `hallmark`? With remark defaults, lists look like this (two spaces):
```markdown
-  foo
-  bar
```
With `hallmark` they look like (single space):
```markdown
- foo
- bar
```
> Replace remark with hallmark

- README.md
- lib/levelup.js
- test/init-test.js
LevelDown supports an [optional `options` argument](https://github.com/Level/abstract-leveldown#dbopenoptions-callback) passed the `db.open` method.  Currently LevelUp fails if options are passed to `.open` as it tries to invoke them as the callback so this PR adds support for that.
By and large you don't call `.open` directly but if you do (or an intermediate module does as in my case) LevelUp should probably honour the api.
> Support options passed to .open

- README.md
- lib/levelup.js
- package.json
- test/clear-test.js
- test/index.js
Closes #648.
~~Blocked by https://github.com/Level/deferred-leveldown/pull/72 and https://github.com/Level/encoding-down/pull/89.~~
> Add clear()

- .gitignore
- .npmignore
- package.json
- test/batch-test.js
- test/deferred-open-test.js
- test/get-put-del-test.js
- test/index.js
- test/read-stream-test.js
- test/self.js
- test/snapshot-test.js
- test/util/rs-factory.js
Closes #273. Doesn't fully achieve what that ticket describes (being able to call the test suite externally would require moving devDependencies to dependencies, or moving the whole thing to its own module), but there's no use case for that anymore. So, this PR is more about being able to reuse the test suite _internally_. This allows us to test feature parity between `levelup` and `abstract-leveldown` (https://github.com/Level/community/issues/58).
> Create test suite

- README.md
- lib/levelup.js
- test/init-test.js
Closes #656. Ref https://github.com/Level/subleveldown/pull/79#issuecomment-536915443.
> Fix floating promise in constructor

- lib/levelup.js
It's a node core module that isn't declared as a dep of this module so modules depending on this one have to declare it separately when using bundlers that don't polyfill node core.
Usage of it here seems unnecessary and can be replaced with a simple equality check.
> chore: remove use of assert module

- .github/codecov.yml
- README.md
- lib/levelup.js
- package.json
- test/deferred-open-test.js
- test/maybe-error-test.js
- test/open-patchsafe-test.js
- test/self.js
- test/self/manifest-test.js
Ref https://github.com/Level/community/issues/101. Depends on https://github.com/Level/memdown/pull/212, https://github.com/Level/encoding-down/pull/102 and https://github.com/Level/deferred-leveldown/pull/89.
Closes https://github.com/Level/levelup/issues/491.
> Add `db.getMany(keys)`

- README.md
- lib/levelup.js
Ref Level/abstract-leveldown#379, Level/community#83, Level/community#79, Level/levelup#726.
Almost the same as https://github.com/Level/level/pull/207.
> Document new features
