Level/levelup

.travis.yml

Also cut testing time in half.
Before:
After:
/cc @juliangruber

target multiple iojs versions, remove notifications

---

README.md
lib/levelup.js
test/batch-test.js

Closes https://github.com/Level/levelup/issues/141

Batch default type

---

README.md
lib/util.js
test/benchmarks/engines/levelup-nosnappy.js
test/benchmarks/engines/levelup-release.js
test/benchmarks/engines/levelup.js
test/binary-test.js
test/common.js
test/deferred-open-test.js
test/encoding-test.js
test/idempotent-test.js
test/init-test.js
test/inject-encoding-test.js
test/json-test.js
test/null-and-undefined-test.js
test/open-patchsafe-test.js
test/read-stream-test.js

closes #344
Those options are backend specific and only belong there.

Remove rare options

---

package.json
test/optional-leveldown-test.js

See https://github.com/Level/levelup/issues/351

less restrictive on leveldown version

---

.travis.yml
README.md
package.json

If this and https://github.com/Level/levelup/pull/369 are fine we can simply merge this one

Dependencies

---

.travis.yml

Closes https://github.com/Level/levelup/issues/431 (skipped removing the 0.12 part)

add node 8

---

lib/levelup.js
test/.gitignore
test/maybe-error-test.js

maybeError() calls callback synchronously

---

CHANGELOG.md
README.md

Closes https://github.com/Level/levelup/issues/444

add release summary and upgrade guide to changelog

---

README.md

Some low-hanging fruit. Addresses:
- "Node.js-style readable stream": drop the -style suffix
- Prefer "a stream of x" over "a stream where `data` events are x"
- Drop this sentence: "The standard pause(), resume() and destroy() methods are implemented on the ReadStream, as is pipe() (see below). 'data', 'error', 'end' and 'close' events are emitted." Linking to Node.js documentation should suffice.
- Stream options: reorder so that `keys`, `values` and legacy options are last
- "underlying LevelDB store" => "underlying store"
- "records" / "entries" => "entries"
- "key/value pairs" => "key-value pairs"
- "data store" => "store"

Readme: homogenize (first pass)

---

README.md

Readme: more low-hanging fruit

---

README.md

Readme: rewrite intro and relationship to leveldown

---

package.json
test/deferred-open-test.js
test/json-test.js
test/no-encoding-test.js

@ralphtheninja anything else we should test?

Test: queued operation is not serialized

---

CHANGELOG.md

See https://github.com/Level/levelup/releases/tag/v2.0.0

remove commits from changelog, moving log to releases instead

---

.travis.yml

Resolves https://github.com/Level/levelup/issues/471

add node 9

---

README.md
lib/levelup.js
test/batch-test.js

Without a replacement in `abstract-leveldown` because https://github.com/Level/abstract-leveldown/issues/146#issuecomment-348695440.
Todo:

Batch: remove defaulting to 'put'

---

.travis.yml
package.json
test/benchmarks/index.js
test/benchmarks/stream-bench.js
test/common.js
test/create-stream-vs-put-racecondition.js
test/data/browser-throws.js
test/data/browser-works.js
test/deferred-open-test.js
test/idempotent-test.js
test/index.js
test/init-test.js
test/inject-encoding-test.js
test/json-test.js
test/maybe-error-test.js
test/no-encoding-test.js
test/null-and-undefined-test.js
test/open-patchsafe-test.js
test/read-stream-test.js
test/snapshot-test.js

For early review. Tests are passing locally in Chrome, IE10 and IE11. Yet to do:

Prepare for browser tests

---

README.md
lib/levelup.js
test/index.js
test/iterator-test.js

Expose iterator

---

CHANGELOG.md
CONTRIBUTORS.md
LICENSE.md
README.md
UPGRADING.md
package.json

Best to follow the commits (the last one adds a lot of style noise).

Add remark

---

README.md
lib/batch.js
lib/common.js
lib/levelup.js
test/batch-test.js

Closes https://github.com/Level/levelup/issues/603

Batch write options

---

package.json
test/batch-test.js
test/binary-test.js
test/common.js
test/deferred-open-test.js
test/get-put-del-test.js
test/inject-encoding-test.js
test/json-test.js

Replace async devDependency with async-each and run-*

---

test/iterator-test.js

Test seek() integration

---

README.md
lib/batch.js
test/chained-batch-encoding-test.js
test/index.js

Ref https://github.com/Level/levelup/issues/633

Support encoding options on chained batch put() and del()

---

README.md

Ref https://github.com/Level/community/issues/113

Doc-deprecate
